// 
// KeywordTable.cs
//  
// Author:
//       Alex Rønne Petersen <xtzgzorex@gmail.com>
// 
// Copyright (c) 2011 Alex Rønne Petersen
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
using System;
using System.Collections.Generic;
using Mono.Cecil.Cil;

namespace Mono.ILDasm {
	internal static class KeywordTable {
		public static IDictionary<string, string> Keywords { get; private set; }
		
		private static void AddKeywords (params string[] keywords)
		{
			foreach (var kw in keywords)
				Keywords.Add (kw, kw);
		}
		
		static KeywordTable ()
		{
			Keywords = new Dictionary<string, string> ();
			
			AddKeywords (
				// directives
				".assembly",
				".cctor",
				".class",
				".imagebase",
				".corflags",
				".ctor",
				".custom",
				".data",
				".emitbyte",
				".entrypoint",
				".event",
				".export",
				".field",
				".file",
				".fire",
				".get",
				".hash",
				".language",
				".line",
				"#line",
				".locale",
				".locals",
				".maxstack",
				".method",
				".module",
				".mresource",
				".manifestres",
				".namespace",
				".other",
				".override",
				".pack",
				".param",
				".permission",
				".permissionset",
				".property",
				".publickey",
				".publickeytoken",
				".addon",
				".removeon",
				".set",
				".size",
				".stackreserve",
				".subsystem",
				".try",
				".ver",
				".vtable",
				".vtentry",
				".vtfixup",
				".zeroinit",
				".this",
				".base",
				".nester",
				".typelist",
				".mscorlib",
				".localized",
				".pdirect",
				".typedef",
				"#define",
				"#undef",
				"#ifdef",
				"#ifndef",
				"#else",
				"#endif",
				"#include",
				// keywords
				"at",
				"as",
				"implicitcom",
				"implicitres",
				"extern",
				"instance",
				"explicit",
				"default",
				"vararg",
				"unmanaged",
				"cdecl",
				"stdcall",
				"thiscall",
				"fastcall",
				"marshal",
				"in",
				"out",
				"opt",
				"static",
				"public",
				"private",
				"family",
				"initonly",
				"rtspecialname",
				"specialname",
				"assembly",
				"famandassem",
				"famorassem",
				"privatescope",
				"literal",
				"notserialized",
				"value",
				"not_in_gc_heap",
				"interface",
				"sealed",
				"abstract",
				"auto",
				"sequential",
				"ansi",
				"unicode",
				"autochar",
				"bestfit",
				"charmaperror",
				"import",
				"serializable",
				"nested",
				"extends",
				"implements",
				"final",
				"virtual",
				"hidebysig",
				"newslot",
				"unmanagedexp",
				"pinvokeimpl",
				"nomangle",
				"lasterr",
				"winapi",
				"platformapi",
				"native",
				"il",
				"cil",
				"optil",
				"managed",
				"forwardref",
				"runtime",
				"internalcall",
				"synchronized",
				"noinlining",
				"nooptimization",
				"custom",
				"fixed",
				"sysstring",
				"array",
				"variant",
				"currency",
				"syschar",
				"void",
				"bool",
				"int8",
				"int16",
				"int32",
				"int64",
				"float",
				"float32",
				"float64",
				"error",
				"unsigned",
				"uint",
				"uint8",
				"uint16",
				"uint32",
				"uint64",
				"decimal",
				"date",
				"bstr",
				"lpstr",
				"lpwstr",
				"lptstr",
				"objectref",
				"iunknown",
				"idispatch",
				"struct",
				"safearray",
				"int",
				"byvalstr",
				"tbstr",
				"lpvoid",
				"any",
				"lpstruct",
				"null",
				"vector",
				"hresult",
				"carray",
				"userdefined",
				"record",
				"filetime",
				"blob",
				"stream",
				"storage",
				"streamed_object",
				"stored_object",
				"blob_object",
				"cf",
				"clsid",
				"method",
				"class",
				"pinned",
				"modreq",
				"modopt",
				"typedref",
				"property",
				"type",
				"refany",
				"char",
				"wchar",
				"fromunmanaged",
				"callmostderived",
				"retainappdomain",
				"bytearray",
				"with",
				"init",
				"to",
				"catch",
				"filter",
				"finally",
				"fault",
				"handler",
				"tls",
				"field",
				"request",
				"demand",
				"assert",
				"deny",
				"permitonly",
				"linkcheck",
				"inheritcheck",
				"reqmin",
				"reqopt",
				"reqrefuse",
				"prejitgrant",
				"prejitdeny",
				"noncasdemand",
				"noncaslinkdemand",
				"noncasinheritance",
				"nometadata",
				"algorithm",
				"retargetable",
				"legacy",
				"library",
				"x86",
				"amd64",
				"ia64",
				"preservesig",
				"beforefieldinit",
				"alignment",
				"nullref",
				"valuetype",
				"compilercontrolled",
				"reqsecobj",
				"enum",
				"object",
				"string",
				"true",
				"false",
				"on",
				"off",
				"strict",
				"mdtoken",
				"noappdomain",
				"noprocess",
				"nomachine",
				"illegal",
				"unused",
				"wrapper",
				"forwarder");
			
			// opcodes
			foreach (var opCode in typeof (OpCodes).GetFields ())
				AddKeywords (((OpCode) opCode.GetValue (null)).Name);
		}
	}
}
